# Generated by Django 4.1.2 on 2022-10-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_avatar_alter_account_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountFollowing',
        ),
    ]
